---
- name: Ping Test
  hosts: all
  gather_facts: true

  tasks:
    - name: Ping test
      ansible.builtin.ping:
      register: ping_result

    - name: Show ping result
      ansible.builtin.debug:
        msg: "{{ ping_result }}"

    - name: Show host IP address
      ansible.builtin.debug:
        msg: "Host IP: {{ ansible_default_ipv4.address }}"
